name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule: [cron: "40 1 * * 1"] # every Monday at 01:40 UTC

permissions:
  contents: read

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.toolchain}}
      - name: No features
        run: cargo check --no-default-features
      - name: All features
        run: cargo check --all-features
      - name: Examples
        run: cargo check --examples
